QnA/urls.py
from django.contrib import admin
from django.urls import path
from QnA import views  

urlpatterns = [
    path('q_write/', views.q_write, name = 'q_write'),
    path('q_list/', views.q_list, name='q_list'),
    path('q_detail/<str:id>/', views.q_detail, name='q_detail'),
    path('q_edit/<str:id>/', views.q_edit, name='q_edit'),
    path('q_delete/<str:id>/', views.q_delete, name='q_delete'),
    path('q_like/<int:q_id>/', views.q_likes, name="q_likes"),
    #path('q_clip/<int:q_id>/', views.q_clip, name="q_clips"),
    path('q_search/',views.q_search, name = 'q_search'),
]

haireview/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

import main.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.main, name = 'main'),
    path('hashtag', main.views.hashtag, name = 'hashtag'),
    path('m_search/',main.views.m_search, name="m_search"),
    path('h_list', main.views.h_list, name='h_list'),

    path('', include('account.urls')),
    path('', include('free.urls')),
    path('', include('QnA.urls')),
    path('', include('review.urls')),
    path('', include('bookmark.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

review/urls.py
from django.contrib import admin
from django.urls import path
from review import views  

urlpatterns = [
    path('r_write/', views.r_write, name = 'r_write'),
    path('r_list/', views.r_list, name='r_list'),
    path('r_detail/<str:id>/', views.r_detail, name='r_detail'),
    path('r_edit/<str:id>/', views.r_edit, name='r_edit'),
    path('r_delete/<str:id>/', views.r_delete, name='r_delete'),
    path('r_like/<int:r_id>/', views.r_likes, name="r_likes"),
    #path('r_clip/<int:r_id>/', views.r_clip, name="r_clips"),
    path('r_search/', views.r_search, name='r_search'),
]

review/models.py
from django.db import models

# Create your models here.


from tkinter import CASCADE
from django.db import models
from django.utils import timezone

# Create your models here.

class Review(models.Model):
    r_title = models.CharField(max_length=200)
    r_body = models.TextField()
    name = models.ForeignKey('account.Profile', on_delete=models.DO_NOTHING, null = True)
    hashtags = models.ManyToManyField('main.Hashtag', blank = True)
    r_location = models.CharField(max_length=20, null = True, blank = True)
    r_photo = models.ImageField(upload_to='images/', blank = True)
    r_receipt = models.ImageField(upload_to='images/', blank = True)
    r_nickname = models.CharField(max_length=20, null = True, blank = True)
    r_clip = models.ManyToManyField('account.Profile', related_name='r_clip', blank=True)
    r_clicks = models.PositiveIntegerField(default=0, verbose_name='조회수')
    r_date = models.DateTimeField('data published')
    r_user = models.ForeignKey('account.Profile', related_name='r_user', on_delete=models.CASCADE, null=True, default='')
    r_like = models.ManyToManyField('account.Profile', related_name='r_likes', blank=True)
    r_likes = models.PositiveIntegerField(default=0, verbose_name='추천수')

    def __str__(self):
        return self.r_title

    def r_summary(self) : 
        return self.r_title[:20]

    @property
    def r_update_counter(self) :
        self.r_clicks += 1 
        self.save() 


class r_comment(models.Model) :
    def __str__(self) :
        return self.text

    r_id = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='r_comments')
    text = models.CharField(max_length=20)
    create_at = models.DateTimeField(auto_now=True)
    name = models.ForeignKey('account.Profile', on_delete=models.DO_NOTHING, null = True)
    r_parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null = True) 

review/forms.py
from django import forms
from .models import Review, r_comment 

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['r_title','r_body', 'r_location', 'r_photo', 'r_receipt', 'hashtags' ]

class r_commentForm(forms.ModelForm) :
    class Meta :
        model = r_comment
        fields = ['text']

review/views.py
from django.shortcuts import render

# Create your views here.


from email.policy import default
from django.shortcuts import render, redirect, get_object_or_404
from review.forms import ReviewForm, r_commentForm
from django.utils import timezone
from review.models import Review, r_comment
from main.models import Hashtag
from django.http import request

# Create your views here.

#리뷰 작성
def r_write(request, review = None) :
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES, instance = review)

        if form.is_valid():
            review = form.save(commit=False)
            review.r_date = timezone.now() 
            review.save()
            form.save_m2m()
                
            return redirect('r_list')
    else:
        form = ReviewForm(instance = review)
        return render(request, 'r_write.html', {'form':form })

#리뷰 목록
def r_list(request):
    reviews = Review.objects
    r_sort = request.GET.get('sort', '') 
    if r_sort == 'r_clicks':
        reviews = Review.objects.all().order_by('-r_clicks','-r_date')
    else:
        reviews = Review.objects.all().order_by('-r_date')
    return render(request, 'r_list.html', {'reviews':reviews, 'sort':r_sort})

#리뷰 글 상세페이지
def r_detail(request, id):
    review = get_object_or_404(Review, id=id)
    if request.method == "POST" :
        form = r_commentForm(request.POST)
        if form.is_valid() :
            r_comment = form.save(commit = False)
            r_comment.r_id = review
            r_comment.text = form.cleaned_data['text']
            r_comment.save()
            form.save_m2m()
            return redirect('r_detail', id)
            
    else :
        form = r_commentForm()
        return render(request, 'r_detail.html', {'review':review, 'form':form})

#리뷰 수정
def r_edit(request, id):
    review = get_object_or_404(Review, id=id)

    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save(commit=False)
            form.save()
            return redirect('r_list')
    else:
        form = ReviewForm(instance=review)
        return render(request, 'r_edit.html', {'form':form})

#리뷰 삭제
def r_delete(request, id):
    review = get_object_or_404(Review, id=id)
    review.delete()
    return redirect('r_list')

#좋아요 
def r_likes(request, r_id):
    like_b = get_object_or_404(Review, id=r_id)
    if request.name in like_b.r_like.all():
        like_b.r_like.remove(request.name)
        like_b.r_likes -= 1
        like_b.save()
    else:
        like_b.r_like.add(request.name)
        like_b.r_likes += 1
        like_b.save()
    return redirect('/r_detail/' + str(r_id))

#추천수 
def r_clip(request, r_id):
    like_b = get_object_or_404(Review, id=r_id)
    if request.name in like_b.r_clip.all():
        like_b.r_clip.remove(request.name)
        like_b.r_clips -= 1
        like_b.save()
    else:
        like_b.r_clip.add(request.name)
        like_b.r_clips += 1
        like_b.save()
    return redirect('/r_detail/' + str(r_id))

#검색
def r_search(request):
        if request.method == 'POST':
                r_searched = request.POST['r_searched']        
                r_serobj = Review.objects.filter(r_title__contains=r_searched)
                return render(request, 'r_search.html', {'r_searched': r_searched,'r_serobj':r_serobj})
        elif request.method == 'POST' :
                r_searched = request.POST['r_searched']        
                r_serobj = Review.objects.filter(r_body__contains=r_searched)
                return render(request, 'r_search.html', {'r_searched': r_searched,'r_serobj':r_serobj})
        else:       
                return render(request, 'r_search.html', {})

review/templates/r_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>머리뷰</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <!--[if IE 7]>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome-ie7.min.css">
    <![endif]-->
</head>
    
<body>
    <nav class="navbar">
        <ul class="nav_menu">
            <li><a href="{% url 'main' %}"><img id="logo_leo" src="{% static 'img/list/logo4.png' %}"></a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" id="list_now" href="{% url 'r_list' %}">미용실 익명 리뷰</a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'q_list' %}">헤어 Q&A</a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'f_list' %}">자유게시판</a></li>
			<li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'h_list' %}">해시태그</a></li>
        </ul>

        <ul class="nav_user">
            {% if user.is_active %}
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'mypage' user.username %}">{{ user.username }}</a></li>
            <li class="nav_position" id="nav_li">/</li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'logout' %}">로그아웃</a></li>
            {% else %}
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'login' %}">로그인</a></li>
            <li class="nav_position" id="nav_li">/</li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'signup' %}">회원가입</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="D_top">
        <div class="D_top_back" id="D_top_back">
            <div class="D_title">
                {{ review.r_title }}
            </div>
            <div class="D_writer">
                {{ review.name }}
            </div>
            <div class="D_hashtag">
                {% for hashtag in review.hashtags.all %}
                <div class="D_tag">
                    #{{ hashtag.name }}
                </div>
                {% endfor %}
            </div>
            <div class="D_body">
                {{review.r_body}}
			</div>
			{% if review.r_photo %}
			후기 사진 : <br>
			<img src="{{ review.r_photo.url }}" width="250" height="250" alt="r_photo">
			{% endif %}
			<br>
			{% if review.r_receipt %}
			영수증 인증 : <br>
			<img src="{{ review.r_receipt.url }}" width="250" height="250" alt="r_receipt">
			{% endif %}
			
			<br>
			{% for hashtag in review.hashtags.all %}
			<span> {{ hashtag.name }} </span>
			{% endfor %}
			
			<div class="D_contents">
                <div id="d_date">
                    {{review.r_date|date:'Y. m. d'}}
                </div>
                <div id="d_look">
                    <div>
                        <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-eye"
                            viewBox="0 0 16 16">
                            <path
                                d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                        </svg>
                    </div>
                    <div id="d_see">
						{{review.r_update_counter}}
                        {{review.r_clicks}}
                    </div>
                </div>
                <div id="d_like">
                    <a href="{% url 'r_likes' review.id %}">
                        {% if user in review.r_like.all %}
                        <svg class="like-icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                            class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                        </svg>
                        {% else %}
                        <svg class="like-icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                            class="bi bi-heart" viewBox="0 0 16 16">
                            <path
                                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                        </svg>
                        {% endif %}
                    </a>
                </div>
            </div>
            <div class="U_D">
                <a style="text-decoration: none; color: #A7755E;" href="{% url 'r_edit' review.id %}">수정하기</a>
                &nbsp;/&nbsp;
                <a style="text-decoration: none; color: #A7755E;" href="{% url 'r_delete' review.id %}">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="D_bottom">
        <div class="D_bottom_back">
    
            <form id="comment_sort" method="POST" action="{% url 'r_detail' review.id %}">
                {% csrf_token %}
                <div>
					{{ form.as_p }}
				</div>
				<div id="comment_submit">
					<input type="submit" value="submit">
				</div>
            </form>
			{% for r_comment in review.r_comments.all %} 
            <p> {{ r_comment.name }} : {{ r_comment.text }} </p>
			<hr id="comment_hr">
            {% endfor %}
        </div>
    </div>
</body>

</html>

review/templates/r_edit.html
<h1>리뷰게시판 수정 페이지</h1>

{% block content %} 
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %} 
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">수정</button>
</form>
{% endblock %}

review/templates/r_hashtag.html
<h1>리뷰게시판 hashtag 페이지</h1>
{{ error_message }}
    {% csrf_token %} 
    <table>
        {{form.as_table}}
    </table>
    <button type="submit">제출하기</button>
</form>

review/templates/r_list.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>머리뷰</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <!--[if IE 7]>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome-ie7.min.css">
    <![endif]-->
</head>
    
<body>
    <nav class="navbar">
        <ul class="nav_menu">
            <li><a href="{% url 'main' %}"><img id="logo_leo" src="{% static 'img/list/logo4.png' %}"></a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" id="list_now" href="{% url 'r_list' %}">미용실 익명 리뷰</a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'q_list' %}">헤어 Q&A</a></li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'f_list' %}">자유게시판</a></li>
			<li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'h_list' %}">해시태그</a></li>
        </ul>

        <ul class="nav_user">
            {% if user.is_active %}
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'mypage' user.username %}">{{ user.username }}</a></li>
            <li class="nav_position" id="nav_li">/</li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'logout' %}">로그아웃</a></li>
            {% else %}
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'login' %}">로그인</a></li>
            <li class="nav_position" id="nav_li">/</li>
            <li class="nav_position" id="nav_part"><a class="nav_li" href="{% url 'signup' %}">회원가입</a></li>
            {% endif %}
        </ul>
    </nav>

    <div class="list_layout">
        <div class="list_back">

			<div class="list_form">

				<!-- 정렬 -->
				<form method="GET" action="{% url 'r_list' %}">
					<div>
						<select name="sort" id="sort" class="list_sort">
							<option value="r_date" id="r_date">최신순</option>
							<option value="r_clicks" id="r_clicks">조회수순</option>
						</select>
						<button class="list_sort_button" type="submit" value="">정렬</button>
					</div>
				</form>

				<!-- 검색 -->
				<form method="POST" action="{% url 'r_search' %}">
					{% csrf_token %}
					<input class="list_search" type="search" name="r_searched" aria-label="검색창">
					<button class="list_search_button" type="submit"> 검색 </button>
				</form>

				<!-- 글작성 -->
				<a class="list_write" type="submit" href="{% url 'r_write' %}">글쓰기</a>
				
			</div>

            <div class="list_table">
                <table>
                    <!--table에는 grid적용이 안되나봐-->
                    <thead id="list_thead">
                        <tr>
                            <th id="list_th">제목</th>
                            <th id="list_th">작성자</th>
                            <th id="list_th">작성일</th>
                            <th id="list_th">조회수</th>
                            <th id="list_th">추천수</th>
                        </tr>
                    </thead>
                    {% for reviews in reviews.all %}
                    <tbody>
                        <tr>
                            <td id="list_td">
                                <a style="text-decoration: none; color: rgb(111, 111, 111);"
                                    href="{% url 'r_detail' reviews.id %}">{{reviews.r_title}}
                                </a>
                            </td>
                            <td id="list_td">{{ reviews.name }}</td>
                            <td id="list_td">{{ reviews.r_date|date:'Y.m.d' }}</td>
							{{review.r_update_counter}}
                            <td id="list_td">{{ reviews.r_clicks }}</td>
                            <td id="list_td">{{ reviews.r_likes }}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</body>
</html>

review/templates/r_search.html
<h1>리뷰 게시판 검색 페이지</h1>

{% if r_searched %}        
    <h3> 검색하신 {{ r_searched }} 에 관한 정보입니다. </h3>
    <br>

    {% for Review in r_serobj %}   
        후기_제목 : <a href="{% url 'r_detail' Review.id %}">{{Review.r_title}}</a>
        <br>
        {{ Review.r_body  }}

        {% if Review.q_photo %}
            <img src = "{{ Review.r_photo.url }}" width = "250" height = "250" alt = "이미지 입니다."> 
            <br>
        {% endif %}
    {% endfor %}

{% else %}       
    <h1> 찾고 있는 검색어를 검색창에 입력해주세요. </h1>
{% endif %}

review/templates/r_write.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/r_write.css' %}">
	<title>r_write</title>
</head>

<body>
    <nav class="navbar">
        <ul class="nav_menu">
            <li id="logo_nav_img"><a class="nav_li" href="{% url 'main' %}"><img id="logo_leo" src="{% static 'img/create/logo5.png' %}"></a></li>
            <li id="nav_part"><a class="nav_li" href="{% url 'r_list' %}" id="list_now">미용실 익명 리뷰</a></li>
            <li id="nav_part"><a class="nav_li" href="{% url 'q_list' %}">헤어 Q&A</a></li>
            <li id="nav_part"><a class="nav_li" href="{% url 'f_list' %}">자유게시판</a></li>
			<li id="nav_part"><a class="nav_li" href="{% url 'h_list' %}">해시태그</a></li>
        </ul>

        <ul class="nav_user">
            {% if user.is_active %}
            <li id="nav_part"><a class="nav_li" href="{% url 'mypage' user.username %}">{{ user.username }}</a></li>
            <li class="nav_li" id="nav_slash">/</li>
            <li id="nav_part"><a class="nav_li" href="{% url 'logout' %}">로그아웃</a></li>
            {% else %}
            <li id="nav_part"><a class="nav_li" href="{% url 'login' %}">로그인</a></li>
            <li class="nav_li" id="nav_slash">/</li>
            <li id="nav_part"><a class="nav_li" href="{% url 'signup' %}">회원가입</a></li>
            {% endif %}
        </ul>
    </nav>
	{% block content %}
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="hidden" name="csrfmiddlewaretoken"
			value="qG2jqW5dF85CkEHeIUGSVtGb70U6iPuoSnl5cSntXeguv4OqiC9GuMLQ34bAF5s9">
		<label class="form_table"></label>
		<table>
			<tbody>
				<tr>
					<th><label for="id_r_title"></label></th>
					<td>
						<input type="text" name="r_title" maxlength="200" required="" id="id_r_title"
							placeholder="제목을 입력해 주세요.">
					</td>
					<label for="id_r_photo"></label>
					<td>
						<input type="file" name="r_photo" accept="image/*" id="id_r_photo" placeholder="사진 첨부">
					</td>
				</tr>
				<tr>
					<th><label for="id_r_body"></label></th>
					<td>
						<textarea name="r_body" cols="70" rows="10" required="" id="id_r_body"
							placeholder="내용을 입력해 주세요."></textarea>
					</td>
					<label for="id_r_receipt"></label>
					<td>
						<input type="file" name="r_receipt" accept="image/*" id="id_r_receipt" placeholder="영수증 사진 첨부">
					</td>
				</tr>
				<tr>
					<th><label for="id_r_name"></label></th>
					<td>
						<input type="text" name="r_name" maxlength="20" id="id_r_name"
							placeholder="미용실 이름을 입력하세요 ex) A미용실 OO점">
					</td>
				</tr>
				<tr>
					<th><label for="id_r_location"></label></th>
					<td>
						<input type="text" name="r_location" maxlength="20" id="id_r_location" sytle="display:inline"
							placeholder="지역을 입력하세요 ex) OO구 OO동">
					</td>
				</tr>
				<tr>
					<th><label for="id_hashtags"></label></th>
					<td>
						<select name="hashtags" id="id_hashtags" multiple="" placeholder="#미용실 후기"></select>
					</td>
				</tr>
			</tbody>
		</table>
		<button class="r_write" type="submit">작성</button>
	</form>
	{% endblock %}
	<footer>
		Copyright&copy; 성공회대학교 멋쟁이사자처럼 10기 머리뷰
	</footer>
</body>

</html>